### ISSUE TITLE
Figure out how to persist image data

### ISSUE THREAD

**Issue by IAmAnubhavSaini** [IAmAnubhavSaini/jspaint#210]
So that as soon as user comes up to the app again, user gets the last work.

```
saveCanvasState = function (options) {
    var image = context.getImageData(options.startX, options.startY, options.width, options.height);
    CanvasState.push(image);
    // #TODO: Figure out a way to do this.
    // if(LocalStorageAvailable && JSON) {
    //   localStorage.setItem('workingImage', JSON.stringify(image));
    //   localStorage.setItem('workingImageOptions', JSON.stringify(options));
    // }
  };
```

Doesn't work as intended.

**Comment by 1j01** [comment]
You can use [`canvas.toDataURL`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL) (without serializing to JSON). Also it's good to catch errors setting items in localStorage because even if localStorage is "available" there are limits to available storage, and you want to tell the user if there wasn't enough space to save.  You can use this to check whether an error is an out-of-storage error cross-browser (to give a friendlier error message in that case):
```js
var quotaExceeded = err.code === 22 || err.name === "NS_ERROR_DOM_QUOTA_REACHED" || err.number === -2147024882;
```
